package com.github.masalthunlass.complex.resources.schemagen;
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /Users/Will/Desktop/insee-geo-onto.ttl 
 * @author Auto-generated by schemagen on 12 janv. 2013 01:48 
 */
public class INSEE_Geo_Ontology {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://rdf.insee.fr/def/geo#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Version 2.5.4 - 2012-12-21";
    
    public static final Resource AireUrbaine = m_model.createResource( "http://rdf.insee.fr/def/geo#AireUrbaine" );
    
    public static final Resource Arrondissement = m_model.createResource( "http://rdf.insee.fr/def/geo#Arrondissement" );
    
    /** <p>Cette classe n'est utilis�e que pour les arrondissements de Paris, Lyon et 
     *  Marseille</p>
     */
    public static final Resource ArrondissementMunicipal = m_model.createResource( "http://rdf.insee.fr/def/geo#ArrondissementMunicipal" );
    
    /** <p>Canton fran�ais, circonscription d'�lection des conseillers g�n�raux</p> */
    public static final Resource Canton = m_model.createResource( "http://rdf.insee.fr/def/geo#Canton" );
    
    /** <p>Dit aussi 'pseudo-canton', c'est un regroupement d'une ou plusieurs communes 
     *  enti�res</p>
     */
    public static final Resource CantonOuVille = m_model.createResource( "http://rdf.insee.fr/def/geo#CantonOuVille" );
    
    /** <p>Changement de rattachement administratif d'une commune</p> */
    public static final Resource ChangementDeDepartementOuArrondissement = m_model.createResource( "http://rdf.insee.fr/def/geo#ChangementDeDepartementOuArrondissement" );
    
    /** <p>Changement de l'intitul� du territoire</p> */
    public static final Resource ChangementDeNom = m_model.createResource( "http://rdf.insee.fr/def/geo#ChangementDeNom" );
    
    /** <p>Collectivit� territoriale d'outre-mer. Inclut les TOM et les territoires � 
     *  statut particulier.</p>
     */
    public static final Resource CollectiviteTerritoriale = m_model.createResource( "http://rdf.insee.fr/def/geo#CollectiviteTerritoriale" );
    
    public static final Resource Commune = m_model.createResource( "http://rdf.insee.fr/def/geo#Commune" );
    
    /** <p>Cr�ation ou r�tablissemnt d'un territoire</p> */
    public static final Resource CreationOuRetablissement = m_model.createResource( "http://rdf.insee.fr/def/geo#CreationOuRetablissement" );
    
    public static final Resource Departement = m_model.createResource( "http://rdf.insee.fr/def/geo#Departement" );
    
    public static final Resource DeplacementDeLimitesDIRIS = m_model.createResource( "http://rdf.insee.fr/def/geo#DeplacementDeLimitesDIRIS" );
    
    /** <p>�tablissement public de coop�ration intercommunale</p> */
    public static final Resource EPCI = m_model.createResource( "http://rdf.insee.fr/def/geo#EPCI" );
    
    /** <p>�change de parcelles entre territoires</p> */
    public static final Resource EchangeDeParcelles = m_model.createResource( "http://rdf.insee.fr/def/geo#EchangeDeParcelles" );
    
    public static final Resource EchangeParcellesCommunesIrisees = m_model.createResource( "http://rdf.insee.fr/def/geo#EchangeParcellesCommunesIrisees" );
    
    public static final Resource EchangeParcellesHabiteesCommunesIriseesNonIrisees = m_model.createResource( "http://rdf.insee.fr/def/geo#EchangeParcellesHabiteesCommunesIriseesNonIrisees" );
    
    public static final Resource EchangeParcellesInhabiteesCommunesIriseesNonIrisees = m_model.createResource( "http://rdf.insee.fr/def/geo#EchangeParcellesInhabiteesCommunesIriseesNonIrisees" );
    
    public static final Resource FusionDeCommunesIrisees = m_model.createResource( "http://rdf.insee.fr/def/geo#FusionDeCommunesIrisees" );
    
    public static final Resource GrandQuartier = m_model.createResource( "http://rdf.insee.fr/def/geo#GrandQuartier" );
    
    /** <p>Exemples : Communaut� Europ�enne, OCDE, OTAN, Pays arabes ...</p> */
    public static final Resource GroupementDePays = m_model.createResource( "http://rdf.insee.fr/def/geo#GroupementDePays" );
    
    /** <p>Mod�lise des zonages divers d'int�r�t statistique</p> */
    public static final Resource GroupementStatistiqueDeCommunes = m_model.createResource( "http://rdf.insee.fr/def/geo#GroupementStatistiqueDeCommunes" );
    
    /** <p>�lot regroup� pour l'information statistique</p> */
    public static final Resource IRIS = m_model.createResource( "http://rdf.insee.fr/def/geo#IRIS" );
    
    public static final Resource LAU = m_model.createResource( "http://rdf.insee.fr/def/geo#LAU" );
    
    public static final Resource LAU1 = m_model.createResource( "http://rdf.insee.fr/def/geo#LAU1" );
    
    public static final Resource LAU2 = m_model.createResource( "http://rdf.insee.fr/def/geo#LAU2" );
    
    /** <p>Modification de la structure d'un ou plusieurs cantons</p> */
    public static final Resource ModificationCantonale = m_model.createResource( "http://rdf.insee.fr/def/geo#ModificationCantonale" );
    
    public static final Resource ModificationDIRIS = m_model.createResource( "http://rdf.insee.fr/def/geo#ModificationDIRIS" );
    
    public static final Resource ModificationDeGroupement = m_model.createResource( "http://rdf.insee.fr/def/geo#ModificationDeGroupement" );
    
    /** <p>Classe g�n�rique de tous les �v�nements li�s � la cr�ation ou � la modification 
     *  de territoires</p>
     */
    public static final Resource ModificationTerritoriale = m_model.createResource( "http://rdf.insee.fr/def/geo#ModificationTerritoriale" );
    
    public static final Resource NUTS = m_model.createResource( "http://rdf.insee.fr/def/geo#NUTS" );
    
    public static final Resource NUTS1 = m_model.createResource( "http://rdf.insee.fr/def/geo#NUTS1" );
    
    public static final Resource NUTS2 = m_model.createResource( "http://rdf.insee.fr/def/geo#NUTS2" );
    
    public static final Resource NUTS3 = m_model.createResource( "http://rdf.insee.fr/def/geo#NUTS3" );
    
    public static final Resource Pays = m_model.createResource( "http://rdf.insee.fr/def/geo#Pays" );
    
    /** <p>Pays ou subdivision g�opolitique d'un pays</p> */
    public static final Resource PaysOuTerritoire = m_model.createResource( "http://rdf.insee.fr/def/geo#PaysOuTerritoire" );
    
    /** <p>R�gion fran�aise de m�tropole ou d'outre-mer</p> */
    public static final Resource Region = m_model.createResource( "http://rdf.insee.fr/def/geo#Region" );
    
    public static final Resource RetablissementCommunesIssuesDeCommuneIrisees = m_model.createResource( "http://rdf.insee.fr/def/geo#RetablissementCommunesIssuesDeCommuneIrisees" );
    
    public static final Resource ScissionDIRIS = m_model.createResource( "http://rdf.insee.fr/def/geo#ScissionDIRIS" );
    
    /** <p>Suppression ou fusion de territoires</p> */
    public static final Resource SuppressionFusion = m_model.createResource( "http://rdf.insee.fr/def/geo#SuppressionFusion" );
    
    public static final Resource TRIRIS = m_model.createResource( "http://rdf.insee.fr/def/geo#TRIRIS" );
    
    /** <p>Subdivision administrative du territoire fran�ais</p> */
    public static final Resource TerritoireAdministratif = m_model.createResource( "http://rdf.insee.fr/def/geo#TerritoireAdministratif" );
    
    /** <p>Subdivision administrative ou statistique du territoire fran�ais</p> */
    public static final Resource TerritoireFrancais = m_model.createResource( "http://rdf.insee.fr/def/geo#TerritoireFrancais" );
    
    /** <p>Subdivision du territoire fran�ais utilis�e pour la production de statistiques</p> */
    public static final Resource TerritoireStatistique = m_model.createResource( "http://rdf.insee.fr/def/geo#TerritoireStatistique" );
    
    /** <p>Changement de la commune chef-lieu d'un territoire</p> */
    public static final Resource TransfertDeChefLieu = m_model.createResource( "http://rdf.insee.fr/def/geo#TransfertDeChefLieu" );
    
    public static final Resource TypeDEPCI = m_model.createResource( "http://rdf.insee.fr/def/geo#TypeDEPCI" );
    
    public static final Resource TypeDIRIS = m_model.createResource( "http://rdf.insee.fr/def/geo#TypeDIRIS" );
    
    public static final Resource UniteUrbaine = m_model.createResource( "http://rdf.insee.fr/def/geo#UniteUrbaine" );
    
    public static final Resource ZoneDEmploi = m_model.createResource( "http://rdf.insee.fr/def/geo#ZoneDEmploi" );
    
    public static final Resource CA = m_model.createResource( "http://id.insee.fr/codes/geo/typeDEPCI/CA" );
    
    public static final Resource CC = m_model.createResource( "http://id.insee.fr/codes/geo/typeDEPCI/CC" );
    
    public static final Resource CU = m_model.createResource( "http://id.insee.fr/codes/geo/typeDEPCI/CU" );
    
    public static final Resource SAN = m_model.createResource( "http://id.insee.fr/codes/geo/typeDEPCI/SAN" );
    
    public static final Resource A = m_model.createResource( "http://id.insee.fr/codes/geo/typeDIRIS/A" );
    
    public static final Resource D = m_model.createResource( "http://id.insee.fr/codes/geo/typeDIRIS/D" );
    
    public static final Resource H = m_model.createResource( "http://id.insee.fr/codes/geo/typeDIRIS/H" );
    
    public static final Resource Z = m_model.createResource( "http://id.insee.fr/codes/geo/typeDIRIS/Z" );
    
}
