/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /Users/Will/Desktop/ontologie-geoinsee.rdf 
 * @author Auto-generated by schemagen on 13 déc. 2012 05:35 
 */
public class Ontologie_geoinsee {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://rdf.insee.fr/geo/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Version 1.0 - 2006-07-18";
    
    public static final Resource Arrondissement = m_model.createResource( "http://rdf.insee.fr/geo/Arrondissement" );
    
    public static final Resource Arrondissement_municipal = m_model.createResource( "http://rdf.insee.fr/geo/Arrondissement_municipal" );
    
    public static final Resource Canton = m_model.createResource( "http://rdf.insee.fr/geo/Canton" );
    
    /** <p>Changement de rattachement administratif d'une commune</p> */
    public static final Resource Changement_de_departement_ou_arrondissement = m_model.createResource( "http://rdf.insee.fr/geo/Changement_de_departement_ou_arrondissement" );
    
    /** <p>Changement de l'intitulé du territoire</p> */
    public static final Resource Changement_de_nom = m_model.createResource( "http://rdf.insee.fr/geo/Changement_de_nom" );
    
    /** <p>Collectivité territoriale d'outre-mer. Inclut les TOM et les territoires à 
     *  statut particulier.</p>
     */
    public static final Resource Collectivite_territoriale = m_model.createResource( "http://rdf.insee.fr/geo/Collectivite_territoriale" );
    
    public static final Resource Commune = m_model.createResource( "http://rdf.insee.fr/geo/Commune" );
    
    /** <p>Création ou rétablissemnt d'un territoire</p> */
    public static final Resource Creation_ou_retablissement = m_model.createResource( "http://rdf.insee.fr/geo/Creation_ou_retablissement" );
    
    public static final Resource Departement = m_model.createResource( "http://rdf.insee.fr/geo/Departement" );
    
    /** <p>Echange de parcelles entre territoires</p> */
    public static final Resource Echange_de_parcelles = m_model.createResource( "http://rdf.insee.fr/geo/Echange_de_parcelles" );
    
    /** <p>Classe générique de tous les événements liés à la création ou à la modification 
     *  de territoires, principalement de communes</p>
     */
    public static final Resource Evenement = m_model.createResource( "http://rdf.insee.fr/geo/Evenement" );
    
    /** <p>Exemples : Communauté Européenne, OCDE, OTAN, Pays arabes ...</p> */
    public static final Resource Groupement_de_pays = m_model.createResource( "http://rdf.insee.fr/geo/Groupement_de_pays" );
    
    public static final Resource LAU = m_model.createResource( "http://rdf.insee.fr/geo/LAU" );
    
    public static final Resource LAU_1 = m_model.createResource( "http://rdf.insee.fr/geo/LAU_1" );
    
    public static final Resource LAU_2 = m_model.createResource( "http://rdf.insee.fr/geo/LAU_2" );
    
    /** <p>Modification de la structure d'un ou plusieurs cantons</p> */
    public static final Resource Modification_cantonale = m_model.createResource( "http://rdf.insee.fr/geo/Modification_cantonale" );
    
    public static final Resource Modification_de_groupement = m_model.createResource( "http://rdf.insee.fr/geo/Modification_de_groupement" );
    
    public static final Resource NUTS = m_model.createResource( "http://rdf.insee.fr/geo/NUTS" );
    
    public static final Resource NUTS_1 = m_model.createResource( "http://rdf.insee.fr/geo/NUTS_1" );
    
    public static final Resource NUTS_2 = m_model.createResource( "http://rdf.insee.fr/geo/NUTS_2" );
    
    public static final Resource NUTS_3 = m_model.createResource( "http://rdf.insee.fr/geo/NUTS_3" );
    
    public static final Resource Pays = m_model.createResource( "http://rdf.insee.fr/geo/Pays" );
    
    /** <p>Pays ou subdivision géopolitique d'un pays</p> */
    public static final Resource Pays_ou_Territoire = m_model.createResource( "http://rdf.insee.fr/geo/Pays_ou_Territoire" );
    
    public static final Resource Pseudo_canton = m_model.createResource( "http://rdf.insee.fr/geo/Pseudo-canton" );
    
    public static final Resource Region = m_model.createResource( "http://rdf.insee.fr/geo/Region" );
    
    /** <p>Suppression ou fusion de territoires</p> */
    public static final Resource Suppression_fusion = m_model.createResource( "http://rdf.insee.fr/geo/Suppression_fusion" );
    
    /** <p>Subdivision administrative du territoire français</p> */
    public static final Resource Territoire_FR = m_model.createResource( "http://rdf.insee.fr/geo/Territoire_FR" );
    
    /** <p>Changement de la commune chef-lieu d'un territoire</p> */
    public static final Resource Transfert_de_chef_lieu = m_model.createResource( "http://rdf.insee.fr/geo/Transfert_de_chef-lieu" );
    
    public static final Resource Type_administratif = m_model.createResource( "http://rdf.insee.fr/geo/Type_administratif" );
    
    public static final Resource Capitale = m_model.createResource( "http://rdf.insee.fr/geo/Capitale" );
    
    public static final Resource Chef_lieu_de_canton = m_model.createResource( "http://rdf.insee.fr/geo/Chef-lieu_de_canton" );
    
    public static final Resource Prefecture = m_model.createResource( "http://rdf.insee.fr/geo/Prefecture" );
    
    public static final Resource Prefecture_de_region = m_model.createResource( "http://rdf.insee.fr/geo/Prefecture_de_region" );
    
    public static final Resource Sous_prefecture = m_model.createResource( "http://rdf.insee.fr/geo/Sous-prefecture" );
    
    public static final Resource centroide = m_model.createResource( "http://rdf.insee.fr/geo/centroide" );
    
    /** <p>la commune siège des institutions administratives du territoire</p> */
    public static final Resource chef_lieu = m_model.createResource( "http://rdf.insee.fr/geo/chef-lieu" );
    
    /** <p>position géographique de la mairie</p> */
    public static final Resource chef_lieu_de_commune = m_model.createResource( "http://rdf.insee.fr/geo/chef-lieu_de_commune" );
    
    /** <p>date de la modification</p> */
    public static final Resource date = m_model.createResource( "http://rdf.insee.fr/geo/date" );
    
    /** <p>description de la modification</p> */
    public static final Resource description = m_model.createResource( "http://rdf.insee.fr/geo/description" );
    
    /** <p>une subdivision administrative de ce territoire</p> */
    public static final Resource subdivision = m_model.createResource( "http://rdf.insee.fr/geo/subdivision" );
    
    /** <p>La valeur par défaut 'true' indique que le territoire existe actuellement. 
     *  La valeur 'false' indique un territoire mort suite à un événement de modification.</p>
     */
    public static final Resource vivant = m_model.createResource( "http://rdf.insee.fr/geo/vivant" );
    
    /** <p>un territoire ayant une frontière commune</p> */
    public static final Resource voisin = m_model.createResource( "http://rdf.insee.fr/geo/voisin" );
    
}
